# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveStorage::Attachment`.
# Please instead update this file by running `bin/tapioca dsl ActiveStorage::Attachment`.

class ActiveStorage::Attachment
  extend GeneratedRelationMethods

  module GeneratedRelationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(T.untyped) }
    def with_all_variant_records(*args, &blk); end
  end
end
