# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveStorage::VariantRecord`.
# Please instead update this file by running `bin/tapioca dsl ActiveStorage::VariantRecord`.

class ActiveStorage::VariantRecord
  extend GeneratedRelationMethods

  module GeneratedRelationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(T.untyped) }
    def with_attached_image(*args, &blk); end
  end
end
