# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AbstractController::Callbacks`.
# Please instead update this file by running `bin/tapioca dsl AbstractController::Callbacks`.

module AbstractController::Callbacks
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
end
