gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # - gem_name
  # doc: true
  # workers: 5
dsl:
  # Add your `dsl` command parameters here:
  #
  exclude:
  - ActiveJob
  - ActiveRecordAssociations
  - ActiveRecordRelations
  - ActiveRecordColumns
  - ActiveStorage
  - ActiveSupportCurrentAttributes
  - MixedInClassAttributes
  # workers: 5
