# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionText::RichText`.
# Please instead update this file by running `bin/tapioca dsl ActionText::RichText`.

class ActionText::RichText
  extend GeneratedRelationMethods

  module GeneratedRelationMethods
    sig { params(args: T.untyped, blk: T.untyped).returns(T.untyped) }
    def with_attached_embeds(*args, &blk); end
  end
end
