# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionController::ContentSecurityPolicy`.
# Please instead update this file by running `bin/tapioca dsl ActionController::ContentSecurityPolicy`.

module ActionController::ContentSecurityPolicy
  mixes_in_class_methods ::AbstractController::Helpers::ClassMethods
  mixes_in_class_methods ::ActiveSupport::Callbacks::ClassMethods
  mixes_in_class_methods ::AbstractController::Callbacks::ClassMethods
end
