# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionController::EtagWithTemplateDigest`.
# Please instead update this file by running `bin/tapioca dsl ActionController::EtagWithTemplateDigest`.

module ActionController::EtagWithTemplateDigest
  mixes_in_class_methods ::ActionController::ConditionalGet::ClassMethods
end
